services:
  redis:
    image: redis:5
    ports:
      - "6379:6379"

  redis-cluster:
    image: grokzen/redis-cluster:7.0.10
    environment:
      - IP=0.0.0.0
    ports:
      - "7000-7005:7000-7005"
